require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Dashboard::CommentsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dashboard::Comment. As you add validations to Dashboard::Comment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Dashboard::CommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dashboard_comments as @dashboard_comments" do
      comment = Dashboard::Comment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dashboard_comments)).to eq([comment])
    end
  end

  describe "GET show" do
    it "assigns the requested dashboard_comment as @dashboard_comment" do
      comment = Dashboard::Comment.create! valid_attributes
      get :show, {:id => comment.to_param}, valid_session
      expect(assigns(:dashboard_comment)).to eq(comment)
    end
  end

  describe "GET new" do
    it "assigns a new dashboard_comment as @dashboard_comment" do
      get :new, {}, valid_session
      expect(assigns(:dashboard_comment)).to be_a_new(Dashboard::Comment)
    end
  end

  describe "GET edit" do
    it "assigns the requested dashboard_comment as @dashboard_comment" do
      comment = Dashboard::Comment.create! valid_attributes
      get :edit, {:id => comment.to_param}, valid_session
      expect(assigns(:dashboard_comment)).to eq(comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dashboard::Comment" do
        expect {
          post :create, {:dashboard_comment => valid_attributes}, valid_session
        }.to change(Dashboard::Comment, :count).by(1)
      end

      it "assigns a newly created dashboard_comment as @dashboard_comment" do
        post :create, {:dashboard_comment => valid_attributes}, valid_session
        expect(assigns(:dashboard_comment)).to be_a(Dashboard::Comment)
        expect(assigns(:dashboard_comment)).to be_persisted
      end

      it "redirects to the created dashboard_comment" do
        post :create, {:dashboard_comment => valid_attributes}, valid_session
        expect(response).to redirect_to(Dashboard::Comment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dashboard_comment as @dashboard_comment" do
        post :create, {:dashboard_comment => invalid_attributes}, valid_session
        expect(assigns(:dashboard_comment)).to be_a_new(Dashboard::Comment)
      end

      it "re-renders the 'new' template" do
        post :create, {:dashboard_comment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dashboard_comment" do
        comment = Dashboard::Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :dashboard_comment => new_attributes}, valid_session
        comment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dashboard_comment as @dashboard_comment" do
        comment = Dashboard::Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :dashboard_comment => valid_attributes}, valid_session
        expect(assigns(:dashboard_comment)).to eq(comment)
      end

      it "redirects to the dashboard_comment" do
        comment = Dashboard::Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :dashboard_comment => valid_attributes}, valid_session
        expect(response).to redirect_to(comment)
      end
    end

    describe "with invalid params" do
      it "assigns the dashboard_comment as @dashboard_comment" do
        comment = Dashboard::Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :dashboard_comment => invalid_attributes}, valid_session
        expect(assigns(:dashboard_comment)).to eq(comment)
      end

      it "re-renders the 'edit' template" do
        comment = Dashboard::Comment.create! valid_attributes
        put :update, {:id => comment.to_param, :dashboard_comment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dashboard_comment" do
      comment = Dashboard::Comment.create! valid_attributes
      expect {
        delete :destroy, {:id => comment.to_param}, valid_session
      }.to change(Dashboard::Comment, :count).by(-1)
    end

    it "redirects to the dashboard_comments list" do
      comment = Dashboard::Comment.create! valid_attributes
      delete :destroy, {:id => comment.to_param}, valid_session
      expect(response).to redirect_to(dashboard_comments_url)
    end
  end

end
